### ISSUE TITLE
Add support Snowflake Java UDF `RUNTIME_VERSION` option

### ISSUE THREAD

**Issue by btiernay** [stewartbryson/gradle-snowflake#114]
Currently it's not possible to target Java 17 like follows:
```sql
CREATE OR REPLACE FUNCTION execute(arg1 STRING)
RETURNS STRING
LANGUAGE JAVA
RUNTIME_VERSION = '17'
IMPORTS = ('@udf/lib.jar')
HANDLER = 'foo.Handler.execute';
```

**Comment by stewartbryson** [comment]
I’m thinking of keeping the default as 11 to not introduce breaking changes. What do you think?

**Comment by btiernay** [comment]
Makes sense as that's the default in Snowflake 👍

**Comment by stewartbryson** [comment]
Try this out, and let me know if it works for you. Thanks.
